apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rqdao-xgl-cache
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
